name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Frontend
        run: |
          docker build -t us-central1-docker.pkg.dev/gglist1/gglist/frontend:latest ./frontend
          docker push us-central1-docker.pkg.dev/gglist1/gglist/frontend:latest

      - name: Build and Push Backend
        run: |
          docker build -t us-central1-docker.pkg.dev/gglist1/gglist/backend:latest ./backend
          docker push us-central1-docker.pkg.dev/gglist1/gglist/backend:latest

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy gglist-backend \
            --image=us-central1-docker.pkg.dev/gglist1/gglist/backend:latest \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --project=gglist1

      - name: Deploy Frontend to Cloud Run
        run: |
          gcloud run deploy gglist-frontend \
            --image=us-central1-docker.pkg.dev/gglist1/gglist/frontend:latest \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --project=gglist1
